export default{
    "login": "Sedki-Sghairi",
    "id": 67509559,
    "node_id": "MDQ6VXNlcjY3NTA5NTU5",
    "avatar_url": "https://avatars1.githubusercontent.com/u/67509559?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sedki-Sghairi",
    "html_url": "https://github.com/Sedki-Sghairi",
    "followers_url": "https://api.github.com/users/Sedki-Sghairi/followers",
    "following_url": "https://api.github.com/users/Sedki-Sghairi/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sedki-Sghairi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sedki-Sghairi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sedki-Sghairi/subscriptions",
    "organizations_url": "https://api.github.com/users/Sedki-Sghairi/orgs",
    "repos_url": "https://api.github.com/users/Sedki-Sghairi/repos",
    "events_url": "https://api.github.com/users/Sedki-Sghairi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sedki-Sghairi/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Sedki Sghairi",
    "company": null,
    "blog": "",
    "location": "united arab emirates",
    "email": null,
    "hireable": null,
    "bio": "A life-time learner, and a passionate programmer",
    "twitter_username": "Sedki_Sghairi",
    "public_repos": 33,
    "public_gists": 0,
    "followers": 27,
    "following": 2,
    "created_at": "2020-06-27T13:41:49Z",
    "updated_at": "2020-11-01T11:51:52Z"
  
}